# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         BigBench
version:      0.11
version_from: bb
installdirs:  site
requires:
    Math::BigInt:                  1.72

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
